services:
  app:
    build:
      context: .
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  database:
    image: mariadb:10.4.20
    environment:
      MYSQL_DATABASE: sik9
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./db/sik.sql:/docker-entrypoint-initdb.d/sik.sql
      - database_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --silent
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 10
    networks:
      - app-network

volumes:
  database_data:

networks:
  app-network:
    driver: bridge
    name: report-kunjungan-pasien-perpoliklinik-network
